//COMMENTI

GET http://localhost:5050/posts/652eb1e94b54c484317c3117/comments

####
POST http://localhost:5050/posts/652eaed5ad3a02117b8a719c/comments/createComment
Content-Type: application/json

{
  "post":"652eaed5ad3a02117b8a719c",
  "comment": "Prova a commentare",
  "author": "Ema"
}

####
GET http://localhost:5050/posts/652eaed5ad3a02117b8a719c/comments/652eb663dfd87dd0f32371c7

####
DELETE http://localhost:5050/posts/652eaed5ad3a02117b8a719c/comments/652eb663dfd87dd0f32371c7/delete HTTP/1.1

####
PATCH  http://localhost:5050/posts/652eaed5ad3a02117b8a719c/comments/652eb663dfd87dd0f32371c7 HTTP/1.1
Content-Type: application/json

{
  "comment":"Commento MODIFICATO"
}






//CHIAMATE PER I POST
####
GET http://localhost:5050/posts?page=1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2ljY2lvIiwic3VybmFtZSI6IkdpYW5mcmFuY2VzY28iLCJlbWFpbCI6ImVtYUBnbWFpbC5jb20iLCJpYXQiOjE2OTc5MjAzMTksImV4cCI6MTY5ODAwNjcxOX0.JYIjHTRUOKyDrYf5wiybJY6jYAVO3A5HSow8f3nGDEA

####
GET http://localhost:5050/authors/byId/651d3e4114e8904e0f148f2f

####
POST http://localhost:5050/posts/create
Content-Type: application/json

{
  "title":"POST con Ref",
  "category": "Category1",
  "cover": "https://picsum.photos/200/300",
  "author": "Ema",
  "readTime": {"value":2, "unit":"minutes"},
  "content": "Contenuto del post"
}

####
PATCH  http://localhost:5050/posts/6518ab3d5b008c46fa9c HTTP/1.1
Content-Type: application/json

{
  "title":"Post MODIFICATO la seconda volta",
  "category":"General Due",
  "rate":6
}

####
DELETE http://localhost:5050/posts/6518aa405b008c468edffa94 HTTP/1.1








//CHIAMATE PER GLI AUTORI
####
GET http://localhost:5050/authors/

####

POST http://localhost:5050/authors/create
Content-Type: application/json

{
  "name":"Ciccio",
  "surname":"Gianfrancesco",
  "email":"ema@gmail.com",
  "birthday": "14/04/2000",
  "avatar":"Ema",
  "password":"dewdewdwe32"
}


####

PATCH http://localhost:5050/authors/651d3e4114e8904e0f148f2f HTTP/1.1
Content-Type: application/json

{
  "email":1,
  "avatar":"ManuLele"
}

####
DELETE http://localhost:5050/authors/651d38e1f23770f9334f7e34 HTTP/1.1





####
POST http://localhost:5050/send-email HTTP/1.1
Content-Type: application/json

{
  "subject":"email di prova",
  "text":"testo dell'email di prova"
} 

####
PATCH  http://localhost:5050/posts/6533b1837f62877bd27fbe32/coverUpdate HTTP/1.1
Content-Type: application/json

{
  "cover":"prova"
} 

#### //LOGIN

POST http://localhost:5050/login HTTP/1.1
Content-Type: application/json

{
  "email":"ema@gmail.com",
  "password": "dewdewdwe32"
} 