GET http://localhost:5050/posts/

####
POST  http://localhost:5050/posts HTTP/1.1
Content-Type: application/json

{
    "title":"Primo post",
    "category":"General",
    "cover":"https://www.google.com/url?sa=i&url=https%3A%2F%2Fwallpapers.com%2Fwallpapers%2F1920x1080-full-hd-nature-empty-road-trees-around-z6u9c3faplzs5ung.html&psig=AOvVaw1rM7fnJy2IXNeny7Dbzklr&ust=1696198184566000&source=images&cd=vfe&opi=89978449&ved=0CBEQjRxqFwoTCPiev-Ss04EDFQAAAAAdAAAAABAE",
    "price":36,
    "rate":5,
    "author":"Emanuele"
}
